### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sillyfrog** [Otacon/wifi_china_drone_controller#3]
I'm hoping you can provide an open source license for this code. I want to start hacking with it (it's great, thanks for your efforts!), but don't want to do the wrong thing by you if doing that. If I can get things going, I will release my code also.

**Comment by Otacon** [comment]
Hi SillyFrog,
Thanks for getting in touch.
This is just an exercise for me, it's been awhile since I've tried to reverse engineer a network protocol.

This is the license:

There is no license. Do what you want. Make a pull request or create your own repo and app and sell it, create a premium library, extend the functionalities etc... I don't really care: I've published it just because I thought it would be useful for other people. I don't need credits, I don't need social approval, I don't need to advertise myself through github ;)

Obviously, I would be more than happy if people will contribute to this repository making their changes available to everyone and build a single cool multiplatform framework to control a wider range of different drones but that's up to you!

I've still got faith in humanity and opensource 👍
